namespace :mac_and_cheese do
	task :make_mac_and_cheese => [:boil_water, :buy_cheese, :buy_pasta] do
		puts("Making Mac and Cheese")
	end

	task :buy_cheese => [:go_to_store] do
		puts("Buying Cheese")
	end

	task :buy_pasta => [:go_to_store] do
		puts("Buying Pasta")
	end

	task :boil_water => [:buy_pasta, :buy_cheese] do
		puts("Boiling Water")
	end

	task :go_to_store do
		puts("Going to the Store")
	end
end
namespace :pasta do
	task :make_pasta => [:boil_water, :spread_spice] do
		puts("Making Pasta")
	end
	
	task :buy_pasta => [:go_to_store] do
		puts("Buying Pasta")
	end
	
	task :unpacking_pasta => [:buy_pasta] do
		puts("Unpacking Pasta")
	end
	
	task :go_to_store do
		puts("Going to the Store")
	end
	
	task :boil_water => [:unpacking_pasta]do
		puts("Boiling Water")
	end
	
	task :spread_spice do
		puts("Spreading Spices")
	end
	
end


